import Solm.DiffTest.Harness
import Tests.DiffTest.Fixtures.Factory.DiffTarget
import Tests.Pipeline.Vault.DiffTarget

/-!
Generated by `scripts/scaffold.py difftest`: the targets of every `DiffTarget.lean` in the
repository.  Do not edit; rerun the script after adding or removing a target.
-/

namespace Tests.DiffTest

def generatedTargets : List Solm.DiffTest.Target :=
  [ Tests.DiffTest.Fixtures.Factory.diffTarget,
    Tests.Pipeline.Vault.diffTarget ]

end Tests.DiffTest
