import Solm.DiffTest.Harness
import Benchmarks.Morpho.MetaMorphoV1_1.DiffTarget
import Benchmarks.Morpho.MetaMorphoV1_1.FixedBlue.DiffTarget
import Tests.DiffTest.Fixtures.Factory.DiffTarget
import Tests.Pipeline.Vault.DiffTarget

/-!
Generated by `scripts/scaffold.py difftest`: the targets of every `DiffTarget.lean` in the
repository.  Do not edit; rerun the script after adding or removing a target.
-/

namespace Tests.DiffTest

def generatedTargets : List Solm.DiffTest.Target :=
  [ Benchmarks.Morpho.MetaMorphoV1_1.diffTarget,
    Benchmarks.Morpho.MetaMorphoV1_1.FixedBlue.diffTarget,
    Tests.DiffTest.Fixtures.Factory.diffTarget,
    Tests.Pipeline.Vault.diffTarget ]

end Tests.DiffTest
