import Examples.Pow.Correct
import Examples.Truth.Correct
import Examples.Caller.Correct
import Examples.ERC20.Correct
import Examples.CtorTruth.Correct
import Examples.CtorStore.Correct
import Examples.Ballot.Correct
import Examples.SimpleAuction.Correct
import Examples.OpenZeppelinBench.Ownable2Step.Correct
import Examples.OpenZeppelinBench.AccessControl.Correct
import Examples.OpenZeppelinBench.Pausable.Correct
import Examples.OpenZeppelinBench.ERC6909.Correct
