import Examples.Pow.Correct
import Examples.Truth.Correct
import Examples.Caller.Correct
import Examples.ERC20.Correct
import Examples.CtorTruth.Correct
import Examples.CtorStore.Correct
import Examples.Ballot.Correct
import Examples.SimpleAuction.Correct
import Examples.StringStore.Correct
