import Tests.Pipeline.Vault.Spec
import Tests.Pipeline.Vault.Bytecode
import Tests.Pipeline.Vault.Selectors
import Reasoning.ABI
import Reasoning.Constructor
import Reasoning.Solc
import Reasoning.Storage
import Reasoning.Dispatch
import Reasoning.SolmBody
import Reasoning.WordArithmetic
import Reasoning.Initcode
import Reasoning.MemCascade
import Mathlib.Tactic.IntervalCases
import Tests.Pipeline.Vault.ImmutableCode
import Reasoning.Immutables

/-!
# Vault proof prelude (generated by `scripts/proof_skeleton.py`)

Single import point for the proof files; selector bridges, selector-word facts, and the
immutables plumbing.  Contract-specific helpers shared by several proof files go here too.
-/

open Solm ABI Ethereum Ethereum.EVM Reasoning.Theory Reasoning.Reach
open Reasoning.Immutables
open Tests.Pipeline.Vault.Immutables

namespace Tests.Pipeline.Vault

set_option maxRecDepth 2000000

@[simp] theorem vaultBytecode_size : vaultBytecode.size = 2416 := by
  native_decide +revert

/-- The transition list as its handles. -/
theorem transitions_eq : contract.transitions = [sweepTransition, countTransition, feeBpsTransition, balancesTransition, totalTransition, withdrawTransition, dropLastTransition, ownerTransition, depositTransition, depositorsTransition, tokenTransition] := by
  first | rfl | simp [contract, Syntax.contractSyntax]

/-! ## Selector bridges: each transition's signature hashes to its table entry -/

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf sweepTransition = vaultSelBytes 0` (`sweep(address)`). -/
theorem sweepSelectorOf : selectorOf sweepTransition = vaultSelBytes 0 := by
  have hsig : transitionSigStr sweepTransition = "sweep(address)" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, sweepTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact sweepSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf countTransition = vaultSelBytes 1` (`count()`). -/
theorem countSelectorOf : selectorOf countTransition = vaultSelBytes 1 := by
  have hsig : transitionSigStr countTransition = "count()" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, countTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact countSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf feeBpsTransition = vaultSelBytes 2` (`feeBps()`). -/
theorem feeBpsSelectorOf : selectorOf feeBpsTransition = vaultSelBytes 2 := by
  have hsig : transitionSigStr feeBpsTransition = "feeBps()" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, feeBpsTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact feeBpsSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf balancesTransition = vaultSelBytes 3` (`balances(address)`). -/
theorem balancesSelectorOf : selectorOf balancesTransition = vaultSelBytes 3 := by
  have hsig : transitionSigStr balancesTransition = "balances(address)" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, balancesTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact balancesSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf totalTransition = vaultSelBytes 4` (`total()`). -/
theorem totalSelectorOf : selectorOf totalTransition = vaultSelBytes 4 := by
  have hsig : transitionSigStr totalTransition = "total()" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, totalTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact totalSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf withdrawTransition = vaultSelBytes 5` (`withdraw(uint256)`). -/
theorem withdrawSelectorOf : selectorOf withdrawTransition = vaultSelBytes 5 := by
  have hsig : transitionSigStr withdrawTransition = "withdraw(uint256)" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, withdrawTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact withdrawSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf dropLastTransition = vaultSelBytes 6` (`dropLast()`). -/
theorem dropLastSelectorOf : selectorOf dropLastTransition = vaultSelBytes 6 := by
  have hsig : transitionSigStr dropLastTransition = "dropLast()" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, dropLastTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact dropLastSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf ownerTransition = vaultSelBytes 7` (`owner()`). -/
theorem ownerSelectorOf : selectorOf ownerTransition = vaultSelBytes 7 := by
  have hsig : transitionSigStr ownerTransition = "owner()" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, ownerTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact ownerSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf depositTransition = vaultSelBytes 8` (`deposit(uint256)`). -/
theorem depositSelectorOf : selectorOf depositTransition = vaultSelBytes 8 := by
  have hsig : transitionSigStr depositTransition = "deposit(uint256)" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, depositTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact depositSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf depositorsTransition = vaultSelBytes 9` (`depositors(uint256)`). -/
theorem depositorsSelectorOf : selectorOf depositorsTransition = vaultSelBytes 9 := by
  have hsig : transitionSigStr depositorsTransition = "depositors(uint256)" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, depositorsTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact depositorsSelectorFact

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
/-- `selectorOf tokenTransition = vaultSelBytes 10` (`token()`). -/
theorem tokenSelectorOf : selectorOf tokenTransition = vaultSelBytes 10 := by
  have hsig : transitionSigStr tokenTransition = "token()" := by
    simp [transitionSigStr, ABI.printSignature, transitionSignature, tokenTransition, contract,
      Syntax.contractSyntax, ABI.abiToSigStr, ABI.elemToSigStr, ABI.intTypeToSigStr, show Nat.repr 256 = "256" by decide +kernel]
      <;> decide +kernel
  unfold selectorOf
  rw [hsig]
  exact tokenSelectorFact

/-! ## Selector words as the dispatcher compares them -/

theorem sweepEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨23599714⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 0 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0x01 0x68 0x1a 0x62 ⟨23599714⟩ (by decide)

theorem countEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨107354813⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 1 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0x06 0x66 0x1a 0xbd ⟨107354813⟩ (by decide)

theorem feeBpsEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨615110739⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 2 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0x24 0xa9 0xd8 0x53 ⟨615110739⟩ (by decide)

theorem balancesEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨669136355⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 3 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0x27 0xe2 0x35 0xe3 ⟨669136355⟩ (by decide)

theorem totalEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨769380666⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 4 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0x2d 0xdb 0xd1 0x3a ⟨769380666⟩ (by decide)

theorem withdrawEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨773487949⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 5 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0x2e 0x1a 0x7d 0x4d ⟨773487949⟩ (by decide)

theorem dropLastEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨1311789167⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 6 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0x4e 0x30 0x50 0x6f ⟨1311789167⟩ (by decide)

theorem ownerEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨2376452955⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 7 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0x8d 0xa5 0xcb 0x5b ⟨2376452955⟩ (by decide)

theorem depositEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨3065339685⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 8 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0xb6 0xb5 0x5f 0x25 ⟨3065339685⟩ (by decide)

theorem depositorsEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨3836935033⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 9 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0xe4 0xb2 0xfb 0x79 ⟨3836935033⟩ (by decide)

theorem tokenEvmSelector {cd : ByteArray} (hsz : 4 ≤ cd.size) :
    UInt256.eq ⟨4228666474⟩ (UInt256.shiftRight (uInt256OfByteArray (cd.readBytes 0 32)) ⟨224⟩)
      = if (vaultSelBytes 10 == cd.extract 0 4) then ⟨1⟩ else ⟨0⟩ :=
  evmSelectorDecode hsz 0xfc 0x0c 0x54 0x6a ⟨4228666474⟩ (by decide)

/-! ## Immutables: the valuation's store, its words, and the deployed runtime -/

/-- The immutables a contract deployed with `v` runs with. -/
def immStore (v : VaultImmutables) : Store :=
  (((∅ : Store).insert "feeBps" (.int (Int.ofNat v.feeBps.toNat))).insert "owner" (.address v.owner))

@[simp] theorem immStore_get_feeBps (v : VaultImmutables) :
    (immStore v).get? "feeBps" = some (.int (Int.ofNat v.feeBps.toNat)) := by
  grind [immStore]

@[simp] theorem wordsOf_immStore_feeBps (v : VaultImmutables) :
    wordsOf (immStore v) "feeBps" = EVM.wordOfInt (Int.ofNat v.feeBps.toNat) :=
  wordsOf_of_get (immStore_get_feeBps v) rfl

@[simp] theorem immStore_get_owner (v : VaultImmutables) :
    (immStore v).get? "owner" = some (.address v.owner) := by
  grind [immStore]

@[simp] theorem wordsOf_immStore_owner (v : VaultImmutables) :
    wordsOf (immStore v) "owner" = EVM.Word.ofNat (↑v.owner : Nat) :=
  wordsOf_of_get (immStore_get_owner v) rfl

/-- The runtime deployed with the immutables `v`. -/
def deployedRuntime (v : VaultImmutables) : ByteArray :=
  immutableLayout.deployed vaultBytecode (immStore v)

theorem evalImmutable_feeBps (cfg : Config) (C : ContractDecl) (locals : Store) (evm : EVM.State)
    (v : VaultImmutables) :
    evalExpr? cfg { contract := C, locals := locals, immutables := immStore v } evm
      (.immutable "feeBps") = .ok (.int (Int.ofNat v.feeBps.toNat)) := by
  simp only [evalExpr?, immStore_get_feeBps, EvalResult.ofOption]

theorem evalImmutable_owner (cfg : Config) (C : ContractDecl) (locals : Store) (evm : EVM.State)
    (v : VaultImmutables) :
    evalExpr? cfg { contract := C, locals := locals, immutables := immStore v } evm
      (.immutable "owner") = .ok (.address v.owner) := by
  simp only [evalExpr?, immStore_get_owner, EvalResult.ofOption]

/-- Every patch site is a declared immutable. -/
theorem immutableLayout_keys :
    ∀ site ∈ immutableLayout.sites, site.2.2 ∈ contract.immutables.map (·.name) := by
  decide

/-- A well-typed immutables store runs as the store of some valuation. -/
theorem restrictImmutables_of_fit {imms : Store} (h : immutablesFit contract imms) :
    ∃ v, restrictImmutables contract imms = immStore v := by
  sorry  -- TODO: case on each immutable's value as in Examples/TinyImmutable/Common.lean

/-- The patched runtime has the template's jump destinations (patch sites are push payloads). -/
theorem vaultPatchedValidJumps (v : VaultImmutables) :
    D_J (deployedRuntime v) 0 = D_J vaultBytecode 0 :=
  Layout.D_J_runtime (by native_decide) (by native_decide)

/-- The same fact in the form the block summaries state the code in. -/
theorem vaultPatchedValidJumpsRuntime (v : VaultImmutables) :
    D_J (immutableLayout.runtime vaultBytecode (wordsOf (immStore v))) 0 = D_J vaultBytecode 0 :=
  vaultPatchedValidJumps v

end Tests.Pipeline.Vault
