import Tests.Pipeline.Vault.Constructor
import Tests.Pipeline.Vault.Sweep
import Tests.Pipeline.Vault.Count
import Tests.Pipeline.Vault.FeeBps
import Tests.Pipeline.Vault.Balances
import Tests.Pipeline.Vault.Total
import Tests.Pipeline.Vault.Withdraw
import Tests.Pipeline.Vault.DropLast
import Tests.Pipeline.Vault.Owner
import Tests.Pipeline.Vault.Deposit
import Tests.Pipeline.Vault.Depositors
import Tests.Pipeline.Vault.Token
import Solm.Refine

/-!
# Vault correctness capstone (generated by `scripts/proof_skeleton.py`)

Thin top-level: the selector case split routes each selector to its per-function `…Body`
lemma, the shared revert paths close the rest, and the constructor is packaged into the
whole-contract refinement.
-/

open Solm ABI Ethereum Ethereum.EVM Reasoning.Theory Reasoning.Reach
open Reasoning.Immutables
open Tests.Pipeline.Vault.Immutables

namespace Tests.Pipeline.Vault

set_option maxRecDepth 2000000

theorem vaultBodyReverts_nonPayable (v : VaultImmutables) (t : TransitionDecl)
    (ht : t ∈ contract.transitions) (evm : EVM.State) (callargs : Store)
    (hwv : evm.executionEnv.weiValue ≠ ⟨0⟩) :
    ExecTransitionBody config contract evm callargs t.body .reverted (immStore v) := by
  rw [transitions_eq] at ht
  simp only [List.mem_cons, List.not_mem_nil, or_false] at ht
  rcases ht with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;>
    exact ExecFuncBody.execBlockRevert (blockReverts_nonPayable hwv)

/-- `callvalue ≠ 0` makes the global non-payable guard revert before dispatch. -/
theorem vaultNonPayable {σ σ₀ A I} {g : UInt256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue ≠ ⟨0⟩) :
    runtimeRefinementFor config contract σ σ₀ g A I (immStore v) := by
  exact (vaultX_callvalue_ne (g := Sat256.ofUInt256 g) v hcode hwv).reEquivElim hcode
    fun _ _ hrev => by
      by_cases hdisp : dispatchMsg contract I.calldata = none
      · exact reEquiv_noDispatch hdisp hrev
      · obtain ⟨t, ht⟩ := Option.ne_none_iff_exists'.mp hdisp
        have htmem : t ∈ contract.transitions := by
          rw [dispatchMsg_eq_dispatchList contract I.calldata (by rfl) (by rfl)] at ht
          exact dispatchList_some_mem ht
        by_cases hdec : decodeCalldataWithMode config.abiDecodeMode (t.params.map Param.name)
            (transitionSignature t).paramTypes I.calldata = none
        · exact reEquiv_decodingFailed ht hdec hrev
        · obtain ⟨callargs, hca⟩ := Option.ne_none_iff_exists'.mp hdec
          exact reEquiv_execution ht hca
            (vaultBodyReverts_nonPayable v t htmem
              (initState σ σ₀ (Sat256.ofUInt256 g) A I)
              callargs (by simp only [initState]; exact hwv))
            (by rw [hrev]; exact execResultsEquiv.revert rfl rfl)

theorem vaultNoDispatch {σ σ₀ A I} {g : UInt256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hsize : I.calldata.size < UInt256.size) (hwv : I.weiValue = ⟨0⟩)
    (hnm : ∀ i, i < 11 → (vaultSelBytes i == I.calldata.extract 0 4) = false) :
    runtimeRefinementFor config contract σ σ₀ g A I (immStore v) := by
  by_cases hsz : 4 ≤ I.calldata.size
  · exact (vaultX_noMatch (g := Sat256.ofUInt256 g) v hcode hwv hsz hsize hnm)
      |>.reEquivNoDispatch hcode (vaultDispatch_none_nomatch hnm)
  · have hshort : I.calldata.size < 4 := by omega
    exact (vaultX_short (g := Sat256.ofUInt256 g) v hcode hwv hshort)
      |>.reEquivNoDispatch hcode (vaultDispatch_none_short hshort)

theorem vaultNoSelectorMatches {I : ExecutionEnv}
    (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2)) (h3 : ¬ selIs I (vaultSelBytes 3)) (h4 : ¬ selIs I (vaultSelBytes 4)) (h5 : ¬ selIs I (vaultSelBytes 5)) (h6 : ¬ selIs I (vaultSelBytes 6)) (h7 : ¬ selIs I (vaultSelBytes 7)) (h8 : ¬ selIs I (vaultSelBytes 8)) (h9 : ¬ selIs I (vaultSelBytes 9)) (h10 : ¬ selIs I (vaultSelBytes 10)) :
    ∀ i, i < 11 → (vaultSelBytes i == I.calldata.extract 0 4) = false := by
  intro i hi
  interval_cases i
  · simpa [selIs] using h0
  · simpa [selIs] using h1
  · simpa [selIs] using h2
  · simpa [selIs] using h3
  · simpa [selIs] using h4
  · simpa [selIs] using h5
  · simpa [selIs] using h6
  · simpa [selIs] using h7
  · simpa [selIs] using h8
  · simpa [selIs] using h9
  · simpa [selIs] using h10

theorem vaultCorrect (v : VaultImmutables) :
    runtimeRefinement config (deployedRuntime v) contract (immStore v) := by
  refine ⟨fun σ σ₀ g A I hcode hsize ↦ ?_⟩
  by_cases hwv : I.weiValue = ⟨0⟩
  · by_cases h0 : selIs I (vaultSelBytes 0)
    · exact vaultSweepBody v hcode hsize hwv h0
    · by_cases h1 : selIs I (vaultSelBytes 1)
      · exact vaultCountBody v hcode hsize hwv h1
      · by_cases h2 : selIs I (vaultSelBytes 2)
        · exact vaultFeeBpsBody v hcode hsize hwv h2
        · by_cases h3 : selIs I (vaultSelBytes 3)
          · exact vaultBalancesBody v hcode hsize hwv h3
          · by_cases h4 : selIs I (vaultSelBytes 4)
            · exact vaultTotalBody v hcode hsize hwv h4
            · by_cases h5 : selIs I (vaultSelBytes 5)
              · exact vaultWithdrawBody v hcode hsize hwv h5
              · by_cases h6 : selIs I (vaultSelBytes 6)
                · exact vaultDropLastBody v hcode hsize hwv h6
                · by_cases h7 : selIs I (vaultSelBytes 7)
                  · exact vaultOwnerBody v hcode hsize hwv h7
                  · by_cases h8 : selIs I (vaultSelBytes 8)
                    · exact vaultDepositBody v hcode hsize hwv h8
                    · by_cases h9 : selIs I (vaultSelBytes 9)
                      · exact vaultDepositorsBody v hcode hsize hwv h9
                      · by_cases h10 : selIs I (vaultSelBytes 10)
                        · exact vaultTokenBody v hcode hsize hwv h10
                        · exact vaultNoDispatch v hcode hsize hwv (vaultNoSelectorMatches h0 h1 h2 h3 h4 h5 h6 h7 h8 h9 h10)
  · exact vaultNonPayable v hcode hwv

theorem vaultRuntimeCorrect (imms : Store) (hfit : immutablesFit contract imms) :
    runtimeRefinement config (immutableLayout.deployed vaultBytecode imms) contract
      (restrictImmutables contract imms) := by
  obtain ⟨v, hv⟩ := restrictImmutables_of_fit hfit
  rw [← Reasoning.Immutables.Layout.deployed_restrict immutableLayout_keys, hv]
  exact vaultCorrect v

theorem vaultContractCorrect :
    contractRefinement config vaultCreationBytecode contract :=
  .of_runtime vaultConstructorCorrect vaultRuntimeCorrect

end Tests.Pipeline.Vault
