import Solm.DiffTest.Harness
import Tests.Pipeline.Vault.Spec
import Tests.Pipeline.Vault.Bytecode
import Tests.Pipeline.Vault.ImmutableCode

/-!
# Vault differential-test target (generated by `scripts/scaffold.py difftest`)

Registered in `Tests/DiffTest/Generated.lean`; run with `lake exe solm-difftest --only Vault`.
Adjust `callees` and `words` when the contract needs specific counterparties or amounts.
-/

open Solm Solm.DiffTest

namespace Tests.Pipeline.Vault

def diffTarget : Target :=
  { name := "Vault", contract := contract, config := config, runtime := vaultBytecode,
    initcode := some vaultCreationBytecode,
    -- runtime cases use the store a generated constructor run leaves; the zero valuation
    -- is the fallback
    immutables := initialImmutables contract,
    runtimeCodeOf := some (immutableLayout.deployed vaultBytecode),
    deployedRuntime := true,
    callees := standardCallees, words := [10 ^ 18] }

end Tests.Pipeline.Vault
