import Tests.Pipeline.Vault.Common
import Tests.Pipeline.Vault.RuntimeBlocks_001
import Tests.Pipeline.Vault.RuntimeBlocks_002
import Tests.Pipeline.Vault.RuntimeBlocks_003
import Tests.Pipeline.Vault.RuntimeBlocks_004
import Tests.Pipeline.Vault.RuntimeBlocks_005
import Tests.Pipeline.Vault.RuntimeBlocks_006
import Tests.Pipeline.Vault.RuntimeBlocks_007
import Tests.Pipeline.Vault.RuntimeBlocks_008

/-!
# Vault dispatcher (generated by `scripts/proof_skeleton.py`)

Solm-side dispatch facts and the runtime dispatcher reach lemmas, composed from the block
summaries along the path the compiled dispatcher takes for each selector.
-/

open Solm ABI Ethereum Ethereum.EVM Reasoning.Theory Reasoning.Reach
open Reasoning.Immutables
open Tests.Pipeline.Vault.Immutables

namespace Tests.Pipeline.Vault

set_option maxRecDepth 2000000

/-! ## Solm dispatch: which transition a selector reaches -/

theorem vaultDispatch_sweep {I : ExecutionEnv} 
    (hsel : selIs I (vaultSelBytes 0)) :
    dispatchMsg contract I.calldata = some sweepTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := []) (post := [countTransition, feeBpsTransition, balancesTransition, totalTransition, withdrawTransition, dropLastTransition, ownerTransition, depositTransition, depositorsTransition, tokenTransition])
    (ti := sweepTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp at hu
  · rw [sweepSelectorOf]; exact hsel

theorem vaultDispatch_count {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0))
    (hsel : selIs I (vaultSelBytes 1)) :
    dispatchMsg contract I.calldata = some countTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition]) (post := [feeBpsTransition, balancesTransition, totalTransition, withdrawTransition, dropLastTransition, ownerTransition, depositTransition, depositorsTransition, tokenTransition])
    (ti := countTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
  · rw [countSelectorOf]; exact hsel

theorem vaultDispatch_feeBps {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1))
    (hsel : selIs I (vaultSelBytes 2)) :
    dispatchMsg contract I.calldata = some feeBpsTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition]) (post := [balancesTransition, totalTransition, withdrawTransition, dropLastTransition, ownerTransition, depositTransition, depositorsTransition, tokenTransition])
    (ti := feeBpsTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
  · rw [feeBpsSelectorOf]; exact hsel

theorem vaultDispatch_balances {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2))
    (hsel : selIs I (vaultSelBytes 3)) :
    dispatchMsg contract I.calldata = some balancesTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition, feeBpsTransition]) (post := [totalTransition, withdrawTransition, dropLastTransition, ownerTransition, depositTransition, depositorsTransition, tokenTransition])
    (ti := balancesTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
    · rw [feeBpsSelectorOf]; exact Bool.eq_false_of_not_eq_true h2
  · rw [balancesSelectorOf]; exact hsel

theorem vaultDispatch_total {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2)) (h3 : ¬ selIs I (vaultSelBytes 3))
    (hsel : selIs I (vaultSelBytes 4)) :
    dispatchMsg contract I.calldata = some totalTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition, feeBpsTransition, balancesTransition]) (post := [withdrawTransition, dropLastTransition, ownerTransition, depositTransition, depositorsTransition, tokenTransition])
    (ti := totalTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
    · rw [feeBpsSelectorOf]; exact Bool.eq_false_of_not_eq_true h2
    · rw [balancesSelectorOf]; exact Bool.eq_false_of_not_eq_true h3
  · rw [totalSelectorOf]; exact hsel

theorem vaultDispatch_withdraw {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2)) (h3 : ¬ selIs I (vaultSelBytes 3)) (h4 : ¬ selIs I (vaultSelBytes 4))
    (hsel : selIs I (vaultSelBytes 5)) :
    dispatchMsg contract I.calldata = some withdrawTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition, feeBpsTransition, balancesTransition, totalTransition]) (post := [dropLastTransition, ownerTransition, depositTransition, depositorsTransition, tokenTransition])
    (ti := withdrawTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
    · rw [feeBpsSelectorOf]; exact Bool.eq_false_of_not_eq_true h2
    · rw [balancesSelectorOf]; exact Bool.eq_false_of_not_eq_true h3
    · rw [totalSelectorOf]; exact Bool.eq_false_of_not_eq_true h4
  · rw [withdrawSelectorOf]; exact hsel

theorem vaultDispatch_dropLast {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2)) (h3 : ¬ selIs I (vaultSelBytes 3)) (h4 : ¬ selIs I (vaultSelBytes 4)) (h5 : ¬ selIs I (vaultSelBytes 5))
    (hsel : selIs I (vaultSelBytes 6)) :
    dispatchMsg contract I.calldata = some dropLastTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition, feeBpsTransition, balancesTransition, totalTransition, withdrawTransition]) (post := [ownerTransition, depositTransition, depositorsTransition, tokenTransition])
    (ti := dropLastTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
    · rw [feeBpsSelectorOf]; exact Bool.eq_false_of_not_eq_true h2
    · rw [balancesSelectorOf]; exact Bool.eq_false_of_not_eq_true h3
    · rw [totalSelectorOf]; exact Bool.eq_false_of_not_eq_true h4
    · rw [withdrawSelectorOf]; exact Bool.eq_false_of_not_eq_true h5
  · rw [dropLastSelectorOf]; exact hsel

theorem vaultDispatch_owner {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2)) (h3 : ¬ selIs I (vaultSelBytes 3)) (h4 : ¬ selIs I (vaultSelBytes 4)) (h5 : ¬ selIs I (vaultSelBytes 5)) (h6 : ¬ selIs I (vaultSelBytes 6))
    (hsel : selIs I (vaultSelBytes 7)) :
    dispatchMsg contract I.calldata = some ownerTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition, feeBpsTransition, balancesTransition, totalTransition, withdrawTransition, dropLastTransition]) (post := [depositTransition, depositorsTransition, tokenTransition])
    (ti := ownerTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
    · rw [feeBpsSelectorOf]; exact Bool.eq_false_of_not_eq_true h2
    · rw [balancesSelectorOf]; exact Bool.eq_false_of_not_eq_true h3
    · rw [totalSelectorOf]; exact Bool.eq_false_of_not_eq_true h4
    · rw [withdrawSelectorOf]; exact Bool.eq_false_of_not_eq_true h5
    · rw [dropLastSelectorOf]; exact Bool.eq_false_of_not_eq_true h6
  · rw [ownerSelectorOf]; exact hsel

theorem vaultDispatch_deposit {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2)) (h3 : ¬ selIs I (vaultSelBytes 3)) (h4 : ¬ selIs I (vaultSelBytes 4)) (h5 : ¬ selIs I (vaultSelBytes 5)) (h6 : ¬ selIs I (vaultSelBytes 6)) (h7 : ¬ selIs I (vaultSelBytes 7))
    (hsel : selIs I (vaultSelBytes 8)) :
    dispatchMsg contract I.calldata = some depositTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition, feeBpsTransition, balancesTransition, totalTransition, withdrawTransition, dropLastTransition, ownerTransition]) (post := [depositorsTransition, tokenTransition])
    (ti := depositTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
    · rw [feeBpsSelectorOf]; exact Bool.eq_false_of_not_eq_true h2
    · rw [balancesSelectorOf]; exact Bool.eq_false_of_not_eq_true h3
    · rw [totalSelectorOf]; exact Bool.eq_false_of_not_eq_true h4
    · rw [withdrawSelectorOf]; exact Bool.eq_false_of_not_eq_true h5
    · rw [dropLastSelectorOf]; exact Bool.eq_false_of_not_eq_true h6
    · rw [ownerSelectorOf]; exact Bool.eq_false_of_not_eq_true h7
  · rw [depositSelectorOf]; exact hsel

theorem vaultDispatch_depositors {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2)) (h3 : ¬ selIs I (vaultSelBytes 3)) (h4 : ¬ selIs I (vaultSelBytes 4)) (h5 : ¬ selIs I (vaultSelBytes 5)) (h6 : ¬ selIs I (vaultSelBytes 6)) (h7 : ¬ selIs I (vaultSelBytes 7)) (h8 : ¬ selIs I (vaultSelBytes 8))
    (hsel : selIs I (vaultSelBytes 9)) :
    dispatchMsg contract I.calldata = some depositorsTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition, feeBpsTransition, balancesTransition, totalTransition, withdrawTransition, dropLastTransition, ownerTransition, depositTransition]) (post := [tokenTransition])
    (ti := depositorsTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
    · rw [feeBpsSelectorOf]; exact Bool.eq_false_of_not_eq_true h2
    · rw [balancesSelectorOf]; exact Bool.eq_false_of_not_eq_true h3
    · rw [totalSelectorOf]; exact Bool.eq_false_of_not_eq_true h4
    · rw [withdrawSelectorOf]; exact Bool.eq_false_of_not_eq_true h5
    · rw [dropLastSelectorOf]; exact Bool.eq_false_of_not_eq_true h6
    · rw [ownerSelectorOf]; exact Bool.eq_false_of_not_eq_true h7
    · rw [depositSelectorOf]; exact Bool.eq_false_of_not_eq_true h8
  · rw [depositorsSelectorOf]; exact hsel

theorem vaultDispatch_token {I : ExecutionEnv} (h0 : ¬ selIs I (vaultSelBytes 0)) (h1 : ¬ selIs I (vaultSelBytes 1)) (h2 : ¬ selIs I (vaultSelBytes 2)) (h3 : ¬ selIs I (vaultSelBytes 3)) (h4 : ¬ selIs I (vaultSelBytes 4)) (h5 : ¬ selIs I (vaultSelBytes 5)) (h6 : ¬ selIs I (vaultSelBytes 6)) (h7 : ¬ selIs I (vaultSelBytes 7)) (h8 : ¬ selIs I (vaultSelBytes 8)) (h9 : ¬ selIs I (vaultSelBytes 9))
    (hsel : selIs I (vaultSelBytes 10)) :
    dispatchMsg contract I.calldata = some tokenTransition := by
  refine dispatchMsg_eq_some_of_split (contract := contract)
    (pre := [sweepTransition, countTransition, feeBpsTransition, balancesTransition, totalTransition, withdrawTransition, dropLastTransition, ownerTransition, depositTransition, depositorsTransition]) (post := [])
    (ti := tokenTransition) (cd := I.calldata) (by rfl) ?_ ?_ ?_ (by rfl)
  · exact transitions_eq
  · intro u hu
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hu
    rcases hu with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · rw [sweepSelectorOf]; exact Bool.eq_false_of_not_eq_true h0
    · rw [countSelectorOf]; exact Bool.eq_false_of_not_eq_true h1
    · rw [feeBpsSelectorOf]; exact Bool.eq_false_of_not_eq_true h2
    · rw [balancesSelectorOf]; exact Bool.eq_false_of_not_eq_true h3
    · rw [totalSelectorOf]; exact Bool.eq_false_of_not_eq_true h4
    · rw [withdrawSelectorOf]; exact Bool.eq_false_of_not_eq_true h5
    · rw [dropLastSelectorOf]; exact Bool.eq_false_of_not_eq_true h6
    · rw [ownerSelectorOf]; exact Bool.eq_false_of_not_eq_true h7
    · rw [depositSelectorOf]; exact Bool.eq_false_of_not_eq_true h8
    · rw [depositorsSelectorOf]; exact Bool.eq_false_of_not_eq_true h9
  · rw [tokenSelectorOf]; exact hsel

theorem vaultDispatch_none_short {cd : ByteArray} (h : cd.size < 4) :
    dispatchMsg contract cd = none := by
  rw [dispatchMsg_eq_dispatchList contract cd, transitions_eq]
  refine dispatchList_none_short _ ?_ h
  intro t ht
  simp only [List.mem_cons, List.not_mem_nil, or_false] at ht
  rcases ht with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · rw [sweepSelectorOf]; rfl
  · rw [countSelectorOf]; rfl
  · rw [feeBpsSelectorOf]; rfl
  · rw [balancesSelectorOf]; rfl
  · rw [totalSelectorOf]; rfl
  · rw [withdrawSelectorOf]; rfl
  · rw [dropLastSelectorOf]; rfl
  · rw [ownerSelectorOf]; rfl
  · rw [depositSelectorOf]; rfl
  · rw [depositorsSelectorOf]; rfl
  · rw [tokenSelectorOf]; rfl

theorem vaultDispatch_none_nomatch {I : ExecutionEnv}
    (hnm : ∀ i, i < 11 → (vaultSelBytes i == I.calldata.extract 0 4) = false) :
    dispatchMsg contract I.calldata = none := by
  refine dispatchMsg_none_of_all_ne (contract := contract) (cd := I.calldata) (by rfl) (by rfl) ?_
  intro t ht
  rw [transitions_eq] at ht
  simp only [List.mem_cons, List.not_mem_nil, or_false] at ht
  rcases ht with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · rw [sweepSelectorOf]; exact hnm 0 (by omega)
  · rw [countSelectorOf]; exact hnm 1 (by omega)
  · rw [feeBpsSelectorOf]; exact hnm 2 (by omega)
  · rw [balancesSelectorOf]; exact hnm 3 (by omega)
  · rw [totalSelectorOf]; exact hnm 4 (by omega)
  · rw [withdrawSelectorOf]; exact hnm 5 (by omega)
  · rw [dropLastSelectorOf]; exact hnm 6 (by omega)
  · rw [ownerSelectorOf]; exact hnm 7 (by omega)
  · rw [depositSelectorOf]; exact hnm 8 (by omega)
  · rw [depositorsSelectorOf]; exact hnm 9 (by omega)
  · rw [tokenSelectorOf]; exact hnm 10 (by omega)

/-! ## Runtime dispatcher paths -/

/-- Dispatcher path to `sweep(address)` (arm entry pc 170). -/
theorem vaultReachSweepBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 0)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 170)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨23599714⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0x01 0x68 0x1a 0x62 ⟨23599714⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd2
  have rd4 := vaultBlocks.vault_block_110_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨23599714⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd3
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack, deployedRuntime] using rd4⟩

/-- Dispatcher path to `count()` (arm entry pc 191). -/
theorem vaultReachCountBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 1)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 191)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨107354813⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0x06 0x66 0x1a 0xbd ⟨107354813⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd2
  have rd4 := vaultBlocks.vault_block_110_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨23599714⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_122_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨107354813⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd4
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack, deployedRuntime] using rd5⟩

/-- Dispatcher path to `feeBps()` (arm entry pc 214). -/
theorem vaultReachFeeBpsBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 2)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 214)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨615110739⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0x24 0xa9 0xd8 0x53 ⟨615110739⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd2
  have rd4 := vaultBlocks.vault_block_110_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨23599714⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_122_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨107354813⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd4
  have rd6 := vaultBlocks.vault_block_133_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨615110739⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd5
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack, deployedRuntime] using rd6⟩

/-- Dispatcher path to `balances(address)` (arm entry pc 253). -/
theorem vaultReachBalancesBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 3)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 253)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨669136355⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0x27 0xe2 0x35 0xe3 ⟨669136355⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd2
  have rd4 := vaultBlocks.vault_block_110_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨23599714⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_122_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨107354813⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd4
  have rd6 := vaultBlocks.vault_block_133_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨615110739⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd5
  have rd7 := vaultBlocks.vault_block_144_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨669136355⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd6
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack, deployedRuntime] using rd7⟩

/-- Dispatcher path to `total()` (arm entry pc 284). -/
theorem vaultReachTotalBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 4)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 284)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨769380666⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0x2d 0xdb 0xd1 0x3a ⟨769380666⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd2
  have rd4 := vaultBlocks.vault_block_110_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨23599714⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_122_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨107354813⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd4
  have rd6 := vaultBlocks.vault_block_133_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨615110739⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd5
  have rd7 := vaultBlocks.vault_block_144_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨669136355⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd6
  have rd8 := vaultBlocks.vault_block_155_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨769380666⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd7
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack, deployedRuntime] using rd8⟩

/-- Dispatcher path to `withdraw(uint256)` (arm entry pc 293). -/
theorem vaultReachWithdrawBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 5)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 293)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨773487949⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0x2e 0x1a 0x7d 0x4d ⟨773487949⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd2
  have rd4 := vaultBlocks.vault_block_41_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨773487949⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd3
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack, deployedRuntime] using rd4⟩

/-- Dispatcher path to `dropLast()` (arm entry pc 312). -/
theorem vaultReachDropLastBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 6)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 312)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨1311789167⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0x4e 0x30 0x50 0x6f ⟨1311789167⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd2
  have rd4 := vaultBlocks.vault_block_41_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_52_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨1311789167⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd4
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack, deployedRuntime] using rd5⟩

/-- Dispatcher path to `owner()` (arm entry pc 320). -/
theorem vaultReachOwnerBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 7)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 320)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨2376452955⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0x8d 0xa5 0xcb 0x5b ⟨2376452955⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd2
  have rd4 := vaultBlocks.vault_block_41_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_52_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨1311789167⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd4
  have rd6 := vaultBlocks.vault_block_63_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨2376452955⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd5
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack, deployedRuntime] using rd6⟩

/-- Dispatcher path to `deposit(uint256)` (arm entry pc 383). -/
theorem vaultReachDepositBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 8)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 383)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨3065339685⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0xb6 0xb5 0x5f 0x25 ⟨3065339685⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd2
  have rd4 := vaultBlocks.vault_block_41_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_52_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨1311789167⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd4
  have rd6 := vaultBlocks.vault_block_63_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨2376452955⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd5
  have rd7 := vaultBlocks.vault_block_74_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨3065339685⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd6
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack, deployedRuntime] using rd7⟩

/-- Dispatcher path to `depositors(uint256)` (arm entry pc 402). -/
theorem vaultReachDepositorsBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 9)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 402)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨3836935033⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0xe4 0xb2 0xfb 0x79 ⟨3836935033⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd2
  have rd4 := vaultBlocks.vault_block_41_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_52_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨1311789167⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd4
  have rd6 := vaultBlocks.vault_block_63_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨2376452955⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd5
  have rd7 := vaultBlocks.vault_block_74_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨3065339685⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd6
  have rd8 := vaultBlocks.vault_block_85_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨3836935033⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd7
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack, deployedRuntime] using rd8⟩

/-- Dispatcher path to `token()` (arm entry pc 421). -/
theorem vaultReachTokenBody {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩) (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hsel : selIs I (vaultSelBytes 10)) :
    ∃ k C, RD (deployedRuntime v) I g (initState σ σ₀ g A I) (UInt256.ofNat 421)
      [(UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes (⟨0⟩ : UInt256).toNat 32)) (UInt256.ofNat 224))]
      ((UInt256.ofNat 128).toByteArray.write 0 ByteArray.empty (UInt256.ofNat 64).toNat 32)
      (M (UInt256.ofNat 0) (UInt256.ofNat 64) (⟨32⟩ : UInt256)) ByteArray.empty σ k C := by
  have hword : solcSelectorWord I = ⟨4228666474⟩ :=
    solcSelectorWord_eq_of_beq I hsz 0xfc 0x0c 0x54 0x6a ⟨4228666474⟩ (by native_decide)
      (by simpa [vaultSelBytes] using hsel)
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
  have rd3 := vaultBlocks.vault_block_25_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd2
  have rd4 := vaultBlocks.vault_block_41_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd3
  have rd5 := vaultBlocks.vault_block_52_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨1311789167⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd4
  have rd6 := vaultBlocks.vault_block_63_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨2376452955⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd5
  have rd7 := vaultBlocks.vault_block_74_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨3065339685⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd6
  have rd8 := vaultBlocks.vault_block_85_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨3836935033⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [hword]; native_decide)) rd7
  have rd9 := vaultBlocks.vault_block_96_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨4228666474⟩ (solcSelectorWord I)) ≠ ⟨0⟩ by rw [hword]; native_decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd8
  exact ⟨_, _, by simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack, deployedRuntime] using rd9⟩

/-- `callvalue ≠ 0` reverts in the global non-payable guard -/
theorem vaultX_callvalue_ne {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue ≠ ⟨0⟩) :
    RDrev (deployedRuntime v) g (initState σ σ₀ g A I) := by
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_fallthrough (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) rd0
  have rd2 := vaultBlocks.vault_block_12 (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_fallthrough_stack, vaultBlocks.vault_block_0_fallthrough_memory]) rd1
  simpa [vaultBlocks.vault_block_0_fallthrough_stack, vaultBlocks.vault_block_0_fallthrough_memory, deployedRuntime] using rd2

/-- Calldata shorter than a selector -/
theorem vaultX_short {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩)
    (hshort : I.calldata.size < 4) :
    RDrev (deployedRuntime v) g (initState σ σ₀ g A I) := by
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
  have rd2 := vaultBlocks.vault_block_15_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd1
  have rd3 := vaultBlocks.vault_block_166 (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_taken_stack]) rd2
  simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_taken_stack, deployedRuntime] using rd3

/-- No selector matches (binary-search dispatcher: case split on each pivot). -/
theorem vaultX_noMatch {σ σ₀ A I} {g : Sat256} (v : VaultImmutables)
    (hcode : I.code = deployedRuntime v) (hwv : I.weiValue = ⟨0⟩)
    (hsz : 4 ≤ I.calldata.size) (hsize : I.calldata.size < UInt256.size)
    (hnm : ∀ i, i < 11 → (vaultSelBytes i == I.calldata.extract 0 4) = false) :
    RDrev (deployedRuntime v) g (initState σ σ₀ g A I) := by
  have rd0 := RD.initState (g := g) (σ := σ) (σ₀ := σ₀) (A := A) hcode
  by_cases hpiv0 : (UInt256.gt ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩
  · -- pivot at pc 40: not taken
    have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
    have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
    have rd3 := vaultBlocks.vault_block_25_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using hpiv0) rd2
    have rd4 := vaultBlocks.vault_block_41_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨773487949⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, withdrawEvmSelector hsz, hnm 5 (by omega)]; decide)) rd3
    have rd5 := vaultBlocks.vault_block_52_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨1311789167⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, dropLastEvmSelector hsz, hnm 6 (by omega)]; decide)) rd4
    have rd6 := vaultBlocks.vault_block_63_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨2376452955⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, ownerEvmSelector hsz, hnm 7 (by omega)]; decide)) rd5
    have rd7 := vaultBlocks.vault_block_74_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨3065339685⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, depositEvmSelector hsz, hnm 8 (by omega)]; decide)) rd6
    have rd8 := vaultBlocks.vault_block_85_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨3836935033⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, depositorsEvmSelector hsz, hnm 9 (by omega)]; decide)) rd7
    have rd9 := vaultBlocks.vault_block_96_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨4228666474⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, tokenEvmSelector hsz, hnm 10 (by omega)]; decide)) rd8
    have rd10 := vaultBlocks.vault_block_107 (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack]) rd9
    simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_fallthrough_stack, deployedRuntime] using rd10
  · -- pivot at pc 40: taken
    have rd1 := vaultBlocks.vault_block_0_taken (immWords := wordsOf (immStore v)) (by simp) (by first | (rw [hwv]; decide) | exact isZero_eq_zero_of_ne hwv | exact hwv | simpa using hwv) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd0
    have rd2 := vaultBlocks.vault_block_15_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory]) (by first | exact lt_four_eq_zero_of_ge hsz hsize | exact lt_four_ne_zero_of_lt hshort | exact isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort) | (rw [lt_four_eq_zero_of_ge hsz hsize]; decide) | (rw [isZero_eq_zero_of_ne (lt_four_ne_zero_of_lt hshort)]; decide)) rd1
    have rd3 := vaultBlocks.vault_block_25_taken (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack]) (by simpa [solcSelectorWord] using hpiv0) (by rw [vaultPatchedValidJumpsRuntime v]; jump_dest) rd2
    have rd4 := vaultBlocks.vault_block_110_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨23599714⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, sweepEvmSelector hsz, hnm 0 (by omega)]; decide)) rd3
    have rd5 := vaultBlocks.vault_block_122_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨107354813⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, countEvmSelector hsz, hnm 1 (by omega)]; decide)) rd4
    have rd6 := vaultBlocks.vault_block_133_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨615110739⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, feeBpsEvmSelector hsz, hnm 2 (by omega)]; decide)) rd5
    have rd7 := vaultBlocks.vault_block_144_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨669136355⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, balancesEvmSelector hsz, hnm 3 (by omega)]; decide)) rd6
    have rd8 := vaultBlocks.vault_block_155_fallthrough (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) (by simpa [solcSelectorWord] using (show (UInt256.eq ⟨769380666⟩ (solcSelectorWord I)) = ⟨0⟩ by rw [solcSelectorWord, totalEvmSelector hsz, hnm 4 (by omega)]; decide)) rd7
    have rd9 := vaultBlocks.vault_block_166 (immWords := wordsOf (immStore v)) (by simp [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack]) rd8
    simpa [vaultBlocks.vault_block_0_taken_stack, vaultBlocks.vault_block_0_taken_memory, vaultBlocks.vault_block_15_fallthrough_stack, vaultBlocks.vault_block_25_taken_stack, deployedRuntime] using rd9

end Tests.Pipeline.Vault
