import Solm.Syntax
import EVM.Types

/-!
# Vault immutable valuation and offset table

Generated by `scripts/scaffold.py lean` from solc's `evm.deployedBytecode.immutableReferences`
(solc `0.8.35+commit.47b9dedd.Darwin.appleclang`).  `runtime.hex` is the runtime template with every
immutable site zeroed; the constructor patches the sites in the order listed below, which is
the order the creation code writes them.
-/

open Solm ABI

namespace Tests.Pipeline.Vault.Immutables

/-- A valuation of the contract's immutables, as the runtime proofs consume them. -/
structure VaultImmutables where
  feeBps : EVM.Word
  owner : EVM.Address

/-- solc `immutableReferences`: each immutable's Solm name and patch offsets, in the order the
    constructor writes them. -/
def immutableReferences : List (Ident × List Nat) :=
  [ ("feeBps", [219, 1591]),
    ("owner", [325, 450, 1239]) ]

end Tests.Pipeline.Vault.Immutables
