import Ethereum.Semantics

/-!
# Vault selectors

Generated by `scripts/scaffold.py lean`: the selector table in `contract.transitions` order,
the selector predicates, and one kernel-checked keccak fact per ABI signature.  The bridge from
each Solm transition's signature string to its entry (`transitionSigStr … = "…"`) is added by
the proof skeleton once `Spec.lean` exists.
-/

open Ethereum Ethereum.EVM

namespace Tests.Pipeline.Vault

/-- The 4-byte selector word computed by `CALLDATALOAD(0); SHR 224`. -/
abbrev vaultSelWord (I : ExecutionEnv) : UInt256 :=
  UInt256.shiftRight (uInt256OfByteArray (I.calldata.readBytes 0 32)) ⟨224⟩

/-- The 4-byte selector of `I`'s calldata equals `sel`. -/
abbrev selIs (I : ExecutionEnv) (sel : ByteArray) : Prop :=
  (sel == I.calldata.extract 0 4) = true

/-- Function selectors in `contract.transitions` order (11 entries). -/
def vaultSelBytes : ℕ → ByteArray
  | 0 => ⟨#[0x01, 0x68, 0x1a, 0x62]⟩  -- sweep(address)
  | 1 => ⟨#[0x06, 0x66, 0x1a, 0xbd]⟩  -- count()
  | 2 => ⟨#[0x24, 0xa9, 0xd8, 0x53]⟩  -- feeBps()
  | 3 => ⟨#[0x27, 0xe2, 0x35, 0xe3]⟩  -- balances(address)
  | 4 => ⟨#[0x2d, 0xdb, 0xd1, 0x3a]⟩  -- total()
  | 5 => ⟨#[0x2e, 0x1a, 0x7d, 0x4d]⟩  -- withdraw(uint256)
  | 6 => ⟨#[0x4e, 0x30, 0x50, 0x6f]⟩  -- dropLast()
  | 7 => ⟨#[0x8d, 0xa5, 0xcb, 0x5b]⟩  -- owner()
  | 8 => ⟨#[0xb6, 0xb5, 0x5f, 0x25]⟩  -- deposit(uint256)
  | 9 => ⟨#[0xe4, 0xb2, 0xfb, 0x79]⟩  -- depositors(uint256)
  | _ => ⟨#[0xfc, 0x0c, 0x54, 0x6a]⟩  -- token()

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

/-- `keccak256("sweep(address)")[0:4] = 0x01681a62`. -/
theorem sweepSelectorFact :
    (Ethereum.KEC (String.toByteArray "sweep(address)")).extract 0 4 = vaultSelBytes 0 := by
  decide +kernel

/-- `keccak256("count()")[0:4] = 0x06661abd`. -/
theorem countSelectorFact :
    (Ethereum.KEC (String.toByteArray "count()")).extract 0 4 = vaultSelBytes 1 := by
  decide +kernel

/-- `keccak256("feeBps()")[0:4] = 0x24a9d853`. -/
theorem feeBpsSelectorFact :
    (Ethereum.KEC (String.toByteArray "feeBps()")).extract 0 4 = vaultSelBytes 2 := by
  decide +kernel

/-- `keccak256("balances(address)")[0:4] = 0x27e235e3`. -/
theorem balancesSelectorFact :
    (Ethereum.KEC (String.toByteArray "balances(address)")).extract 0 4 = vaultSelBytes 3 := by
  decide +kernel

/-- `keccak256("total()")[0:4] = 0x2ddbd13a`. -/
theorem totalSelectorFact :
    (Ethereum.KEC (String.toByteArray "total()")).extract 0 4 = vaultSelBytes 4 := by
  decide +kernel

/-- `keccak256("withdraw(uint256)")[0:4] = 0x2e1a7d4d`. -/
theorem withdrawSelectorFact :
    (Ethereum.KEC (String.toByteArray "withdraw(uint256)")).extract 0 4 = vaultSelBytes 5 := by
  decide +kernel

/-- `keccak256("dropLast()")[0:4] = 0x4e30506f`. -/
theorem dropLastSelectorFact :
    (Ethereum.KEC (String.toByteArray "dropLast()")).extract 0 4 = vaultSelBytes 6 := by
  decide +kernel

/-- `keccak256("owner()")[0:4] = 0x8da5cb5b`. -/
theorem ownerSelectorFact :
    (Ethereum.KEC (String.toByteArray "owner()")).extract 0 4 = vaultSelBytes 7 := by
  decide +kernel

/-- `keccak256("deposit(uint256)")[0:4] = 0xb6b55f25`. -/
theorem depositSelectorFact :
    (Ethereum.KEC (String.toByteArray "deposit(uint256)")).extract 0 4 = vaultSelBytes 8 := by
  decide +kernel

/-- `keccak256("depositors(uint256)")[0:4] = 0xe4b2fb79`. -/
theorem depositorsSelectorFact :
    (Ethereum.KEC (String.toByteArray "depositors(uint256)")).extract 0 4 = vaultSelBytes 9 := by
  decide +kernel

/-- `keccak256("token()")[0:4] = 0xfc0c546a`. -/
theorem tokenSelectorFact :
    (Ethereum.KEC (String.toByteArray "token()")).extract 0 4 = vaultSelBytes 10 := by
  decide +kernel

end Tests.Pipeline.Vault
