import Tests.Pipeline.Vault.SpecSyntax
import Solm.Semantics
import Solm.SolidityLayout
import Solm.MetaSolidityLayout
import Solm.Refine

import Tests.Pipeline.Vault.Immutables
/-!
# Vault spec assembly (generated by `scripts/proof_skeleton.py`)

The contract is defined by `SpecSyntax.lean`; this file only names its parts: the transition
handles the proof files unfold, the storage backend (solc's standard layout, from the
declarations), the external-call ABI, and the `Config`.
-/

open Solm ABI

namespace Tests.Pipeline.Vault

def contract : ContractDecl := Syntax.contractSyntax

/-! ## Transition handles, in `contract.transitions` order -/

abbrev sweepTransition : TransitionDecl := contract.transitions[0]!  -- sweep(address)
abbrev countTransition : TransitionDecl := contract.transitions[1]!  -- count()
abbrev feeBpsTransition : TransitionDecl := contract.transitions[2]!  -- feeBps()
abbrev balancesTransition : TransitionDecl := contract.transitions[3]!  -- balances(address)
abbrev totalTransition : TransitionDecl := contract.transitions[4]!  -- total()
abbrev withdrawTransition : TransitionDecl := contract.transitions[5]!  -- withdraw(uint256)
abbrev dropLastTransition : TransitionDecl := contract.transitions[6]!  -- dropLast()
abbrev ownerTransition : TransitionDecl := contract.transitions[7]!  -- owner()
abbrev depositTransition : TransitionDecl := contract.transitions[8]!  -- deposit(uint256)
abbrev depositorsTransition : TransitionDecl := contract.transitions[9]!  -- depositors(uint256)
abbrev tokenTransition : TransitionDecl := contract.transitions[10]!  -- token()

/-! ## Storage backend: solc's layout for the declared storage -/

def storageBackend : StorageBackend := solidityStorage! [contract.structs] [contract.storage]

/-! ## External-call ABI (from the translator's call facts; check against the callee ABIs) -/

def selectorBytes (a b c d : UInt8) : ByteArray := ⟨#[a, b, c, d]⟩

def externalABI : ExternalCallABI where
  encode? := fun name args =>
    if False then none
    else if name = "transferFrom" then  -- transferFrom(address,address,uint256)
      ABI.encodeCallWithSelector? (selectorBytes 0x23 0xb8 0x72 0xdd) [(.elem .address), (.elem .address), (.elem (.int (.uint ⟨256, by decide⟩)))] args
    else if name = "transfer" then  -- transfer(address,uint256)
      ABI.encodeCallWithSelector? (selectorBytes 0xa9 0x05 0x9c 0xbb) [(.elem .address), (.elem (.int (.uint ⟨256, by decide⟩)))] args
    else if name = "balanceOf" then  -- balanceOf(address)
      ABI.encodeCallWithSelector? (selectorBytes 0x70 0xa0 0x82 0x31) [(.elem .address)] args
    else none
  decode? := fun name out =>
    if False then none
    else if name = "transferFrom" then
      (ABI.decodeReturnValueWithMode? DecodeMode.modern (.elem .bool) out).map (fun v => [v])
    else if name = "transfer" then
      (ABI.decodeReturnValueWithMode? DecodeMode.modern (.elem .bool) out).map (fun v => [v])
    else if name = "balanceOf" then
      (ABI.decodeReturnValueWithMode? DecodeMode.modern (.elem (.int (.uint ⟨256, by decide⟩))) out).map (fun v => [v])
    else none

/-! ## Config -/

def config : Config :=
  { storageBackend := storageBackend
    externalABI := externalABI
    selfDeployment := genSolidityConstructorDeployment contract.ctor.params }

end Tests.Pipeline.Vault
