import Solm.Notation

/-!
# Vault spec draft (generated by `scripts/sol2solm.py`)

Source contract `Vault`, solc 0.8.35; linearisation: Vault.
Transitions are in selector order (the dispatcher order).

External calls (for the spec's `ExternalCallABI`):
  - transferFrom(address, address, uint256) returns (bool)
  - transfer(address, uint256) returns (bool)
  - balanceOf(address) view returns (uint256)
-/

open Solm Solm.Notation

namespace Tests.Pipeline.Vault.Syntax

def contractSyntax : ContractDecl := solidity% contract Vault {
  address immutable owner;
  uint256 immutable feeBps;
  address token;
  mapping(address => uint256) balances;
  address[] depositors;
  uint256 total;
  bool transient locked;

  event Deposit(address indexed «from», uint256 amount);
  event Withdraw(address indexed «to», uint256 amount);

  constructor(address token_, uint256 feeBps_) {
    require(feeBps_ <= 10000);
    owner = msg.sender;
    feeBps = feeBps_;
    token = token_;
  }

  function sweep(address «to») external {
    require(msg.sender == owner);
    require(!(locked));
    locked = true;
    var held = token.balanceOf{view}(address(this));
    require(held > total);
    var __c1 = token.transfer(«to», ((held - total) as uint256));
    require(__c1);
    locked = false;
  }

  function count() external returns (uint256) {
    return depositors.length;
  }

  function feeBps() external returns (uint256) {
    return feeBps;
  }

  function balances(address arg0) external returns (uint256) {
    return balances[arg0];
  }

  function total() external returns (uint256) {
    return total;
  }

  function withdraw(uint256 amount) external {
    require(!(locked));
    locked = true;
    require(balances[msg.sender] >= amount);
    balances[msg.sender] = ((balances[msg.sender] - amount) as uint256);
    total = ((total - amount) as uint256);
    var __c0 = token.transfer(msg.sender, amount);
    require(__c0);
    emit Withdraw(msg.sender, amount);
    locked = false;
  }

  function dropLast() external {
    require(msg.sender == owner);
    depositors.pop();
  }

  function owner() external returns (address) {
    return owner;
  }

  function deposit(uint256 amount) external {
    require(!(locked));
    locked = true;
    require(amount > 0);
    var __c0 = token.transferFrom(msg.sender, address(this), amount);
    require(__c0);
    uint256 net = (amount - (((amount * feeBps) as uint256) / 10000)) as uint256;
    if (balances[msg.sender] == 0) {
      depositors.push(msg.sender);
    }
    balances[msg.sender] = ((balances[msg.sender] + net) as uint256);
    total = ((total + net) as uint256);
    emit Deposit(msg.sender, net);
    locked = false;
  }

  function depositors(uint256 arg0) external returns (address) {
    return depositors[arg0];
  }

  function token() external returns (address) {
    return token;
  }

}

end Tests.Pipeline.Vault.Syntax
