import Solm.Examples.Pow.Correct
import Solm.Examples.Truth.Correct
import Solm.Examples.Caller.Correct
import Solm.Examples.ERC20.Correct
import Solm.Examples.CtorTruth.Correct
import Solm.Examples.CtorStore.Correct
import Solm.Examples.TinyImmutable.Correct
import Solm.Examples.Ballot.Correct
import Solm.Examples.SimpleAuction.Correct
import Solm.Examples.StringStoreLite.Correct
import Solm.Examples.BlindAuction.Correct
import Solm.Examples.OpenZeppelinBench.Ownable2Step.Correct
import Solm.Examples.OpenZeppelinBench.AccessControl.Correct
import Solm.Examples.OpenZeppelinBench.Pausable.Correct
import Solm.Examples.OpenZeppelinBench.ERC6909.Correct
import Solm.Examples.UniswapV2Pair.Correct
import Solm.Examples.Reuse.Correct
import Solm.Examples.VyperERC20.Correct
