import Solm.DiffTest.Harness
import Tests.DiffTest.Fixtures.Factory.Spec
import Tests.DiffTest.Fixtures.Factory.Bytecode

/-!
# Factory differential-test target (generated by `scripts/scaffold.py difftest`)

Registered in `Tests/DiffTest/Generated.lean`; run with `lake exe solm-difftest --only Factory`.
Adjust `callees` and `words` when the contract needs specific counterparties or amounts.
-/

open Solm Solm.DiffTest

namespace Tests.DiffTest.Fixtures.Factory

def diffTarget : Target :=
  { name := "Factory", contract := contract, config := config, runtime := factoryBytecode,
    initcode := some factoryCreationBytecode,
    callees := standardCallees, words := [10 ^ 18] }

end Tests.DiffTest.Fixtures.Factory
