import Solidity.Test.Specs.Truth
import Solidity.Test.Specs.Pow
import Solidity.Test.Specs.Caller
import Solidity.Test.Specs.Reuse
import Solidity.Test.Specs.CtorStore
import Solidity.Test.Specs.CtorTruth
import Solidity.Examples.ERC20.Spec
import Solidity.Test.Specs.StringStoreLite
import Solidity.Test.Specs.TinyImmutable
import Solidity.Test.Specs.Ballot
import Solidity.Test.Specs.SimpleAuction
import Solidity.Test.Specs.BlindAuction
import Solidity.Test.Specs.Ownable2Step
import Solidity.Test.Specs.AccessControl
import Solidity.Test.Specs.Pausable
import Solidity.Test.Specs.ERC6909
import Solidity.Test.Specs.Factory
import Solidity.Test.Specs.HexLit
import Solidity.Test.Specs.TryCatch
import Solidity.Test.Specs.BaseCall
import Solidity.Test.Specs.Ecrecover
import Solidity.Test.Specs.Fixes
